version: "3.9"

services:
  dcreative:
    image: flashspys/nginx-static
    container_name: zerodrink.dcreative.cz
    restart: "always"
    volumes:
      - ./web:/static:ro
    labels:
      - "traefik.http.routers.zerodrink_https.rule=Host(`zerodrink.dcreative.cz`)"
      - "traefik.http.routers.zerodrink_https.entrypoints=websecure"
      - "traefik.http.routers.zerodrink_https.tls=true"
      - "traefik.http.routers.zerodrink_https.tls.certResolver=lets-encrypt"

networks:
  default:
    name: web